### ISSUE TITLE
`code` styling in hover box is bright red

### ISSUE THREAD

**Issue by ezracelli** [o4x/base16-tomorrow-vscode#1]
Heya! Love the theme, the darker sidebar puts it miles ahead of the other Tomorrow Night-based VSCode themes 💪 Only thing that's kind of annoying is:

![image](https://user-images.githubusercontent.com/6758913/80986009-f67f4680-8dfd-11ea-8266-891ae84468d9.png)

**Comment by o4x** [comment]
Hi @ezracelli thank for helpful feedback, I fix your issue, now you can try using the version `0.2.0`. For more details you can check [CHANGELOG](https://github.com/o4x/base16-tomorrow-vscode/blob/master/CHANGELOG.md).
