### ISSUE TITLE
Selected element not highlighted in suggestions

### ISSUE THREAD

**Issue by pabueco** [o4x/base16-tomorrow-vscode#2]
First of, I really like the colors of this theme. Looks great!

However, while using it I found a little issue that is quite annoying.

The selected element inside the suggestions is not highlighted.

In this screenshot, the first suggestion is selected/focussed but you can't tell since there is not visual difference to the rest. 

![image](https://user-images.githubusercontent.com/25956751/90631011-4d305500-e222-11ea-8c8c-8fe602069343.png)

It would be nice if the current element would be highlighted.

**Comment by o4x** [comment]
Hi @pabueco , yep you're right. I will fix it soon...

**Comment by pabueco** [comment]
@o4x Great! Thank you for this awesome theme.

**Comment by o4x** [comment]
Thank you for communicate and report this.
